### ISSUE TITLE
The Alert message does not replace the previous one

### ISSUE THREAD

**Issue by majdzik84** [Jopyth/MMM-Remote-Control#256] opened 2021-03-28 19:07 UTC
Hello. I don't know if the problem concerns the module or the magic mirror software, so forgive me if I am writing about it in the wrong place.

I noticed that the Alert message does not replace the previous one if it is currently displayed.

I don't know when it happened, however it used to work without a problem. 

I am attaching a video.

https://user-images.githubusercontent.com/31352476/112764548-592a9380-9009-11eb-8540-a79ff8218be8.mp4

**Comment by ezeholz** [comment] 2021-03-28 19:41
Alright, I'll check the code in a few days.

In the meantime, could you please let me know which version of MM and Remote Control you're using?

Also, what do you do when this happens? You use the API, the alert menu? It's automatic or manual?

With that information, I might be able to solve this issue or hotfix it until MM solves it, if it's another problem.
Cheers!

**Comment by majdzik84** [comment] 2021-03-28 20:17
Thank you very much.

I have the version:
Magic mirror: 2.15.0 -develop (this bug also appeared on the official one)
MMM-Remote - I do not see any update available, so probably the latest.

The situation occurs both when sending an alert menu via Remote and with API.

I use the API and send the following command automatically by HA:
`http://192.168.2.200:8080/api/module/alert/showalert?message=SZOPA&timer=60000&imageHeight=650px&imageUrl=https://xxxx./local/snapshots/szopa.jpg%3Fdupa= {{as_timestamp (now ()) )}}`

**Comment by ezeholz** [comment] 2021-04-08 23:48
It seems that the timer is giving problems, If you use 30000 for example, the problem isn't happening to me. Let me know if that's working for you too.

**Comment by majdzik84** [comment] 2021-04-09 07:34
Unfortunately, changing the time does not change anything for me.
Even when there is no timer assigned, the alerts behave the same way :(

**Comment by ezeholz** [comment] 2021-04-09 12:52
It could be that MM is hiding the alert just when it shows up. I would recommend that you try hiding it before sending another. Let me know if that works.

We can't do much here, because MM hides the first alert automatically. And the reason of this happening could be lag, delaying the hiding action until the last alert take place, and then hiding both.

If that works, maybe we could try to modify the MM code for you, so that it works out. But every update you'll have to change it again.

**Comment by majdzik84** [comment] 2021-04-09 18:52
The method of hiding an alert and resending another one works fine.
Can you suggest how to modify the mm code?

**Comment by ezeholz** [comment] 2021-04-10 07:40
In the meantime, you could replace this lines from the file `MagicMirror/modules/default/alert/notificationFx.js`:

In line 130, and you'll have the following:
```
setTimeout(() => {
    this.ntf.classList.add("ns-hide");

    //callback
    this.options.onClone();
}, 25);
```

Select all that, and replace it with:
```
this.ntf.classList.add("ns-hide");
```

That way you'll not have any trouble with using the alert module.
I'm now adding this inside MM GitHub bugs, so this should be fixed soon.

Thanks for letting me know this!
Cheers :D

**Comment by majdzik84** [comment] 2021-04-11 18:31
Thank you very much. Works as it should!

**Comment by ezeholz** [comment] 2021-04-14 16:18
Just for you to know, the next version of MM comes with this fix. So you can update your MM safely when comes out.
I'm gonna close this issue now. But feel free to create another one if you have any other problem.
Cheers! :D

**Closed by ezeholz** 2021-04-14 16:18 UTC
Labels: bug
